In [1]:
import pandas as pd

In [4]:
# Necessary Libraries
import numpy as np              # For numeric operations
import pandas as pd             # For data manipulation and analysis
import matplotlib.pyplot as plt # For data visualization
%matplotlib inline              

# To visualize text
from wordcloud import WordCloud

# For Naturla Language Processing
import nltk
from nltk.corpus import stopwords

# Downloading NLTK data
nltk.download('stopwords') # Downloading stopwords data
nltk.download('punkt')     # Downloading tokenizer data

[nltk_data] Downloading package stopwords to C:\Users\Gangotri
[nltk_data]     Mishra\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to C:\Users\Gangotri
[nltk_data]     Mishra\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [5]:
# Read CSV file
df = pd.read_csv('spam.csv')

# Display the first few rows of DataFrame
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [6]:
# Removing unnecessary columns
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'], inplace= True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
# Columns name change
df.rename(columns={'v1': 'target', 'v2': 'text'}, inplace= True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

# Data Pre-processing

In [13]:
from sklearn.preprocessing import LabelEncoder

# Encoding text to numerical
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [17]:
# Check duplicate values
df.duplicated().sum()

# Drop duplicate
df = df.drop_duplicates(keep='first')
len(df)

5169

# Feature Engineering

In [18]:
# Importing the Porter stemmer for text Stemming
from nltk.stem.porter import PorterStemmer

# Importing the string module for handling special characters
import string

# Creating an instance of the Porter Stemmer
ps = PorterStemmer()

In [ ]:
# Lowercase transformation and text preprocessing function
def transform_text(text):
    # Transform text to lowercase
    text = text.lower()

    # Tokenization using NLTK
    text = nltk.word_tokenize(text)

In [20]:
email = " alice.  singh@example.com "

In [24]:
email.strip()

'alice.singh@example.com'

In [28]:
cnt = 3
psswd = 'python123'
a = True
while a:
    if cnt < 3:
        x = input("password enter")
        if x is psswd:
            print("Login Successful")
            break
        else:
            cnt = cnt - 1
    else:
        a = False

In [27]:
as

SyntaxError: invalid syntax (1239779345.py, line 1)